sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:sky_take_out}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  alioss:
    endpoint: ${ALIYUN_ENDPOINT:oss-ap-southeast-1.aliyuncs.com}
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID:}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucketName: ${ALIYUN_BUCKET2:sky-take-out-yauweng}
  spring:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
