server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}


mybatis:
  mapper-locations: classpath*:com/itheima/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # ✅ 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.itheima: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug

aliyun:
  oss:
    endpoint: ${sky.alioss.endpoint}
    accessKeyId: ${sky.alioss.accessKeyId}
    accessKeySecret: ${sky.alioss.accessKeySecret}
    bucketName: ${sky.alioss.bucketName}

sky:
  jwt:
    #设置jwt签名加密时使用的密钥
    admin-secret-key: "itcast-very-long-secret-key-for-jwt-123456"
    #设置jwt过期时间
    admin-ttl: 7200000000
    #设置前端传递过来的令牌名称
    admin-token-name: token
    #设置jwt签名加密时使用的密钥
    user-secret-key: "itcast-very-long-secret-key-for-jwt-123456"
    #设置jwt过期时间
    user-ttl: 7200000000
    #设置前端传递过来的令牌名称
    user-token-name: authentication


springdoc:
  packages-to-scan: com.itheima.controller
